apiVersion: v1
kind: Pod
metadata:
  name: test-aws-cli
  namespace: backstage
  labels:
    app: aws-cli
    backstage.io/kubernetes-id: alt8-ssr-1
spec:
  containers:
  - image: brentley/awscli
    command:
      - "/bin/sleep"
      - "9999"
    name: aws
    env:
      - name: AWS_DEFAULT_REGION
        value: us-gov-west-1
  restartPolicy: Never
  terminationGracePeriodSeconds: 3