apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: {{cookiecutter.component_id }}
  description: {{cookiecutter.description | jsonify}}
  annotations:
    github.com/project-slug: {{cookiecutter.destination.git.owner + "/" + cookiecutter.destination.git.name}}
    backstage.io/techdocs-ref: url:{{cookiecutter.storePath}}
spec:
  type: openapi
  lifecycle: production
  owner: {{cookiecutter.owner | jsonify}}
  definition:
    $text: {{cookiecutter.storePath}}/blob/master/openapi.yaml
