version: '3'
services:
  backstage:
    image: backstage
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      GITHUB_TOKEN: 5e50f6c3aa9ef79a8f60abdd85e33d616158190c
      VIRTUAL_HOST: backstage.docker.local
    networks:
      - proxy
      - db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /tmp:/tmp
  db:
    image: postgres
    networks:
      - db
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
networks:
  proxy:
    external:
      name: proxy_proxy
  db:
    driver: overlay
    ipam:
      driver: default
      config:
      - subnet: 172.16.237.0/24